import { useEffect, useMemo, useState } from "react";
import { company, defaultBuyerProfiles, defaultSellerProfiles, documentSteps, exportFiles, fixedText, formSchemas, initialData, profileFields, tableHeaders, clone } from "./exportData.js";
import "./styles.css";
import "./extra.css";

const profileKeys = ["sellerProfileId", "buyerProfileId"];

function Field({ field, value, onChange, sellers, buyers }) {
  const [key, label, type = "text", required] = field;
  if (profileKeys.includes(key)) {
    const options = type === "sellerProfile" ? sellers : buyers;
    return <label className="field wide"><span>{label}{required && " *"}</span><select value={value || ""} onChange={(event) => onChange(key, event.target.value)}><option value="">Select a saved profile</option>{options.map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select><small className="profile-help">Selecting a profile fills its saved details below. These document values remain editable.</small></label>;
  }
  if (type === "textarea") return <label className="field wide"><span>{label}{required && " *"}</span><textarea rows="3" value={value || ""} onChange={(event) => onChange(key, event.target.value)} /></label>;
  return <label className="field"><span>{label}{required && " *"}</span><input type={type} value={value || ""} onChange={(event) => onChange(key, event.target.value)} /></label>;
}

function GoodsTable({ active, rows, onChange }) {
  const headers = tableHeaders[active];
  if (!headers) return null;
  const packing = active === "packingList";
  const edit = (id, key, value) => onChange(rows.map((row) => row.id === id ? { ...row, [key]: value } : row));
  return <section className="card items"><div className="section-title"><div><small>VARIABLE GOODS LINES</small><h2>{headers.join(" · ")}</h2></div></div><div className="table-wrap"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><textarea value={row.packages} onChange={(event) => edit(row.id, "packages", event.target.value)} /></td><td><textarea value={row.description} onChange={(event) => edit(row.id, "description", event.target.value)} /></td><td><input value={row.quantity} onChange={(event) => edit(row.id, "quantity", event.target.value)} /></td>{packing ? <><td><input value={row.gross} onChange={(event) => edit(row.id, "gross", event.target.value)} /></td><td><input value={row.remarks} onChange={(event) => edit(row.id, "remarks", event.target.value)} /></td></> : <><td><input value={row.rate} onChange={(event) => edit(row.id, "rate", event.target.value)} /></td><td><input value={row.amount} onChange={(event) => edit(row.id, "amount", event.target.value)} /></td></>}</tr>)}</tbody></table></div></section>;
}

function FixedText({ active }) { return <section className="source-detail"><div><small>FIXED PRINTED TEXT</small><h2>Retained from the supplied {documentSteps.find((step) => step.id === active).title} form</h2></div><ol>{fixedText[active].map((line) => <li key={line}>{line}</li>)}</ol></section>; }

function Preview({ active, data }) {
  const step = documentSteps.find((item) => item.id === active);
  const schema = formSchemas[active]; const headers = tableHeaders[active]; const rows = data.documentItems?.[active] || [];
  return <article className="a4"><header><div><h3>{company.name}</h3><p>IEC:- {company.iec} &nbsp; CIN:- {company.cin} &nbsp; GSTIN:- {company.gstin}</p><p>{company.address}</p><p>CONTACT:- {company.phone} &nbsp; E-MAIL:- {company.email}</p></div><b>{step.title}</b></header><hr /><div className="print-fields">{schema.filter(([key]) => !profileKeys.includes(key)).map(([key, label]) => <div key={key}><b>{label}</b><span>{data[key] || "-"}</span></div>)}</div>{headers && <table className="print-table"><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.packages}</td><td>{row.description}</td><td>{row.quantity}</td><td>{active === "packingList" ? row.gross : row.rate}</td><td>{active === "packingList" ? row.remarks : row.amount}</td></tr>)}</tbody></table>}<section className="print-terms"><b>FIXED PRINTED TEXT</b><ol>{fixedText[active].map((line) => <li key={line}>{line}</li>)}</ol></section><footer><span>For, {company.name}</span><span>AUTHORIZED SIGNATORY</span></footer></article>;
}

function Profiles({ sellers, buyers, setSellers, setBuyers, onBack }) {
  const [kind, setKind] = useState("seller"); const profiles = kind === "seller" ? sellers : buyers; const setProfiles = kind === "seller" ? setSellers : setBuyers;
  const [selectedId, setSelectedId] = useState(profiles[0]?.id || "");
  useEffect(() => setSelectedId(profiles[0]?.id || ""), [kind]);
  const selected = profiles.find((profile) => profile.id === selectedId) || profiles[0];
  const update = (key, value) => setProfiles((current) => current.map((profile) => profile.id === selected?.id ? { ...profile, [key]: value } : profile));
  const add = () => { const id = `${kind}-${Date.now()}`; setProfiles((current) => [...current, { id, name: `New ${kind}`, address: "", contact: "", email: "", gstin: "" }]); setSelectedId(id); };
  return <div className="shell"><aside><div className="brand"><i>GA</i><div><b>Gurukrupan</b><small>Export documents</small></div></div><button className="new" onClick={onBack}>← Back to forms</button></aside><main><header className="top"><div><p>LOCAL DIRECTORY</p><h1>Party profiles</h1></div></header><div className="content"><section className="card"><div className="section-title"><div><small>REUSABLE DETAILS</small><h2>Seller and buyer profiles</h2></div><button className="validate" onClick={add}>+ Add {kind}</button></div><div className="profile-tabs"><button className={kind === "seller" ? "chosen" : ""} onClick={() => setKind("seller")}>Sellers</button><button className={kind === "buyer" ? "chosen" : ""} onClick={() => setKind("buyer")}>Buyers / Consignees</button></div><label className="field wide"><span>SELECT {kind.toUpperCase()}</span><select value={selected?.id || ""} onChange={(event) => setSelectedId(event.target.value)}>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><div className="fields">{profileFields.map(([key, label]) => <Field key={key} field={[key, label, key === "address" ? "textarea" : "text"]} value={selected?.[key] || ""} onChange={(_, value) => update(key, value)} sellers={sellers} buyers={buyers} />)}</div><p className="message good">Changes are saved locally. Select this profile in a form to pre-fill the latest saved details. The document can still be edited independently.</p></section></div></main></div>;
}

function App() {
  const [files, setFiles] = useState(() => { try { return JSON.parse(localStorage.getItem("gurukrupan-export-files-v2")) || exportFiles; } catch { return exportFiles; } });
  const [sellers, setSellers] = useState(() => { try { return JSON.parse(localStorage.getItem("gurukrupan-seller-profiles")) || defaultSellerProfiles; } catch { return defaultSellerProfiles; } });
  const [buyers, setBuyers] = useState(() => { try { return JSON.parse(localStorage.getItem("gurukrupan-buyer-profiles")) || defaultBuyerProfiles; } catch { return defaultBuyerProfiles; } });
  const [fileId, setFileId] = useState(files[0]?.id || ""); const [active, setActive] = useState("purchaseOrder"); const [view, setView] = useState("form"); const [notice, setNotice] = useState("");
  const file = files.find((item) => item.id === fileId) || files[0]; const data = file?.data || clone(initialData); const step = documentSteps.find((item) => item.id === active); const schema = formSchemas[active]; const rows = data.documentItems?.[active] || [];
  const total = useMemo(() => rows.reduce((sum, row) => sum + (Number(row.amount) || 0), 0).toFixed(2), [rows]);
  useEffect(() => localStorage.setItem("gurukrupan-export-files-v2", JSON.stringify(files)), [files]); useEffect(() => localStorage.setItem("gurukrupan-seller-profiles", JSON.stringify(sellers)), [sellers]); useEffect(() => localStorage.setItem("gurukrupan-buyer-profiles", JSON.stringify(buyers)), [buyers]);
  const updateFile = (transform) => setFiles((current) => current.map((item) => item.id === file.id ? transform(item) : item));
  const update = (key, value) => { if (profileKeys.includes(key)) { const profile = (key === "sellerProfileId" ? sellers : buyers).find((item) => item.id === value); if (!profile) return; const values = key === "sellerProfileId" ? { sellerProfileId: value, sellerName: profile.name, sellerAddress: profile.address } : { buyerProfileId: value, buyerName: profile.name, buyerAddress: profile.address, buyerContact: profile.contact, buyerEmail: profile.email }; updateFile((item) => ({ ...item, customer: key === "buyerProfileId" ? profile.name : item.customer, data: { ...item.data, ...values } })); } else updateFile((item) => ({ ...item, data: { ...item.data, [key]: value } })); };
  const updateRows = (nextRows) => updateFile((item) => ({ ...item, data: { ...item.data, documentItems: { ...item.data.documentItems, [active]: nextRows } } }));
  const validate = () => { const missing = schema.filter(([key,,,required]) => required && !String(data[key] || "").trim()); if (missing.length) return setNotice(`Missing: ${missing.map(([, label]) => label).join(", ")}`); updateFile((item) => ({ ...item, stage: `${step.title} ready`, data: { ...item.data, completed: { ...item.data.completed, [active]: true } } })); setNotice(`${step.title} saved. You can reopen and edit it any time.`); };
  const newFile = () => { const id = `new-${Date.now()}`; setFiles((current) => [...current, { id, label: `New export · DRAFT-${current.length + 1}`, customer: "", stage: "Draft", data: clone(initialData) }]); setFileId(id); setActive("purchaseOrder"); };
  if (view === "profiles") return <Profiles sellers={sellers} buyers={buyers} setSellers={setSellers} setBuyers={setBuyers} onBack={() => setView("form")} />;
  return <div className="shell"><aside><div className="brand"><i>GA</i><div><b>Gurukrupan</b><small>Export documents</small></div></div><button className="new" onClick={newFile}>+ New export file</button><button className="profiles-link" onClick={() => setView("profiles")}>Manage seller & buyer profiles</button><p className="nav-title">EXPORT FILES</p><div className="file-list">{files.map((item) => <button className={`file-select ${item.id === file.id ? "selected" : ""}`} key={item.id} onClick={() => { setFileId(item.id); setNotice(""); }}><b>{item.label}</b><small>{item.stage}</small></button>)}</div><p className="nav-title">DOCUMENT FLOW</p>{documentSteps.map((item, index) => <button key={item.id} className={`step ${active === item.id ? "active" : ""}`} onClick={() => { setActive(item.id); setNotice(""); }}><i>{index + 1}</i><span><b>{item.title}</b><small>{data.completed?.[item.id] ? "Ready - click to edit" : item.party}</small></span></button>)}</aside><main><header className="top"><div><p>{file.customer || "New export"} / {data.invoiceNo || "Draft"}</p><h1>{step.title}</h1></div><div className="tabs"><button className={view === "form" ? "chosen" : ""} onClick={() => setView("form")}>Edit form</button><button className={view === "preview" ? "chosen" : ""} onClick={() => setView("preview")}>A4 preview</button></div></header>{view === "form" ? <div className="content"><section className="summary"><div><small>SELLER</small><b>{data.sellerName}</b></div><div><small>CONSIGNEE</small><b>{data.buyerName}</b></div><div><small>DOCUMENT TOTAL</small><b>USD {total}</b></div><div><small>STATUS</small><b className={data.completed?.[active] ? "ready" : "draft"}>{data.completed?.[active] ? "Ready" : "Draft"}</b></div></section><section className="card"><div className="section-title"><div><small>{step.party.toUpperCase()} · VARIABLE FIELDS</small><h2>Fields from this specific printed form</h2></div><button className="validate" onClick={validate}>Validate & save</button></div>{notice && <p className={`message ${notice.startsWith("Missing") ? "bad" : "good"}`}>{notice}</p>}<div className="fields">{schema.map((field) => <Field key={field[0]} field={field} value={data[field[0]]} onChange={update} sellers={sellers} buyers={buyers} />)}</div></section><GoodsTable active={active} rows={rows} onChange={updateRows} /><FixedText active={active} /></div> : <div className="preview-area"><div className="preview-bar"><span>Fixed text stays fixed. These values come from this document only.</span><div><button onClick={() => setView("form")}>Back to editing</button><button className="print" onClick={() => window.print()}>Print / save PDF</button></div></div><Preview active={active} data={data} /></div>}</main></div>;
}

export default App;
