import { useEffect, useMemo, useState } from "react";
import { company, defaultBuyerProfiles, defaultSellerProfiles, documentSteps, exportFiles, fixedText, formSchemas, initialData, profileFields, tableHeaders, clone } from "./exportData.js";
import "./styles.css";
import "./extra.css";

const profileKeys = ["sellerProfileId", "buyerProfileId"];

function Field({ field, value, onChange, sellers, buyers }) {
  const [key, label, type = "text", required] = field;
  if (profileKeys.includes(key)) { const options = type === "sellerProfile" ? sellers : buyers; return <label className="field wide"><span>{label}{required && " *"}</span><select value={value || ""} onChange={(e) => onChange(key, e.target.value)}><option value="">Select a saved profile</option>{options.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><small className="profile-help">Select a profile to fill its saved details. This document remains independently editable.</small></label>; }
  if (type === "textarea") return <label className="field wide"><span>{label}{required && " *"}</span><textarea rows="3" value={value || ""} onChange={(e) => onChange(key, e.target.value)} /></label>;
  return <label className="field"><span>{label}{required && " *"}</span><input type={type} value={value || ""} onChange={(e) => onChange(key, e.target.value)} /></label>;
}

function DeleteDialog({ item, onCancel, onConfirm }) {
  if (!item) return null;
  return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="confirm-dialog"><small>CONFIRM DELETE</small><h2>Delete {item.name}?</h2><p>{item.kind === "flow" ? "This permanently deletes this export flow and all of its document values saved on this computer." : "This removes the saved profile. Existing document entries keep their already-filled details."}</p><div><button onClick={onCancel}>Cancel</button><button className="danger" onClick={onConfirm}>Delete permanently</button></div></section></div>;
}

function GoodsTable({ active, rows, onChange }) {
  const headers = tableHeaders[active]; if (!headers) return null; const packing = active === "packingList";
  const edit = (id, key, value) => onChange(rows.map((row) => row.id === id ? { ...row, [key]: value } : row));
  return <section className="card items"><div className="section-title"><div><small>VARIABLE GOODS LINES</small><h2>{headers.join(" · ")}</h2></div></div><div className="table-wrap"><table><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td><textarea value={row.packages} onChange={(e) => edit(row.id, "packages", e.target.value)} /></td><td><textarea value={row.description} onChange={(e) => edit(row.id, "description", e.target.value)} /></td><td><input value={row.quantity} onChange={(e) => edit(row.id, "quantity", e.target.value)} /></td>{packing ? <><td><input value={row.gross} onChange={(e) => edit(row.id, "gross", e.target.value)} /></td><td><input value={row.remarks} onChange={(e) => edit(row.id, "remarks", e.target.value)} /></td></> : <><td><input value={row.rate} onChange={(e) => edit(row.id, "rate", e.target.value)} /></td><td><input value={row.amount} onChange={(e) => edit(row.id, "amount", e.target.value)} /></td></>}</tr>)}</tbody></table></div></section>;
}

function FixedText({ active }) { return <section className="source-detail"><div><small>FIXED PRINTED TEXT</small><h2>Retained from the supplied {documentSteps.find((s) => s.id === active).title} form</h2></div><ol>{fixedText[active].map((line) => <li key={line}>{line}</li>)}</ol></section>; }

function Preview({ active, data }) { const step = documentSteps.find((s) => s.id === active); const schema = formSchemas[active]; const headers = tableHeaders[active]; const rows = data.documentItems?.[active] || []; return <article className="a4"><header><div><h3>{company.name}</h3><p>IEC:- {company.iec} &nbsp; CIN:- {company.cin} &nbsp; GSTIN:- {company.gstin}</p><p>{company.address}</p><p>CONTACT:- {company.phone} &nbsp; E-MAIL:- {company.email}</p></div><b>{step.title}</b></header><hr /><div className="print-fields">{schema.filter(([key]) => !profileKeys.includes(key)).map(([key, label]) => <div key={key}><b>{label}</b><span>{data[key] || "-"}</span></div>)}</div>{headers && <table className="print-table"><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.packages}</td><td>{row.description}</td><td>{row.quantity}</td><td>{active === "packingList" ? row.gross : row.rate}</td><td>{active === "packingList" ? row.remarks : row.amount}</td></tr>)}</tbody></table>}<section className="print-terms"><b>FIXED PRINTED TEXT</b><ol>{fixedText[active].map((line) => <li key={line}>{line}</li>)}</ol></section><footer><span>For, {company.name}</span><span>AUTHORIZED SIGNATORY</span></footer></article>; }

function AppNav({ onDashboard, onProfiles, onNew, backLabel }) { return <aside><div className="brand"><i>GA</i><div><b>Gurukrupan</b><small>Export documents</small></div></div>{backLabel ? <button className="new" onClick={onDashboard}>← {backLabel}</button> : <><button className="new" onClick={onNew}>+ New export flow</button><button className="profiles-link" onClick={onProfiles}>Manage sellers & buyers</button></>}</aside>; }

function Dashboard({ files, onOpen, onNew, onDelete, onProfiles }) { const isReady = (file) => documentSteps.every((step) => file.data.completed?.[step.id]); const activeCount = files.filter((file) => !isReady(file)).length; return <div className="shell"><AppNav onNew={onNew} onProfiles={onProfiles} /><main><header className="top"><div><p>LOCAL EXPORT WORKSPACE</p><h1>Export flows</h1></div><button className="validate" onClick={onNew}>+ New export flow</button></header><div className="content"><section className="dashboard-summary"><div><small>ALL FLOWS</small><b>{files.length}</b></div><div><small>IN PROGRESS</small><b>{activeCount}</b></div><div><small>READY FORMS</small><b>{files.reduce((n, f) => n + Object.values(f.data.completed || {}).filter(Boolean).length, 0)}</b></div></section><section className="flow-grid">{files.length ? files.map((file) => { const complete = Object.values(file.data.completed || {}).filter(Boolean).length; const ready = isReady(file); return <article className={`flow-card ${ready ? "flow-ready" : ""}`} key={file.id}><div><small className={ready ? "status-ready" : "status-progress"}>{ready ? "✓ READY" : "IN PROGRESS"}</small><h2>{file.label}</h2><p>{file.customer || file.data.buyerName || "No consignee selected"}</p></div><div className="flow-progress"><span>{complete} / {documentSteps.length} documents validated</span><i><b style={{ width: `${complete / documentSteps.length * 100}%` }} /></i></div><div className="card-actions"><button className="validate" onClick={() => onOpen(file.id)}>Open & edit</button><button className="secondary" onClick={() => onDelete(file)}>Delete</button></div></article>; }) : <section className="empty-state"><h2>No export flows yet</h2><p>Create your first flow to start entering documents.</p><button className="validate" onClick={onNew}>Create export flow</button></section>}</section></div></main></div>; }

function Profiles({ sellers, buyers, setSellers, setBuyers, onBack, onDelete }) {
  const [kind, setKind] = useState("seller"); const profiles = kind === "seller" ? sellers : buyers; const setProfiles = kind === "seller" ? setSellers : setBuyers;
  const [selectedId, setSelectedId] = useState(""); const [editing, setEditing] = useState(false);
  useEffect(() => { setSelectedId(""); setEditing(false); }, [kind]);
  const selected = profiles.find((p) => p.id === selectedId);
  const update = (key, value) => setProfiles((all) => all.map((p) => p.id === selected?.id ? { ...p, [key]: value } : p));
  const edit = (id) => { setSelectedId(id); setEditing(true); };
  const add = () => { const id = `${kind}-${Date.now()}`; setProfiles((all) => [...all, { id, name: `New ${kind}`, address: "", contact: "", email: "", gstin: "" }]); setSelectedId(id); setEditing(true); };
  return <div className="shell"><AppNav onDashboard={onBack} backLabel="Dashboard" /><main><header className="top"><div><p>LOCAL DIRECTORY</p><h1>Party profiles</h1></div><button className="validate" onClick={add}>+ Add {kind}</button></header><div className="content"><section className="card"><div className="profile-tabs"><button className={kind === "seller" ? "chosen" : ""} onClick={() => setKind("seller")}>Sellers ({sellers.length})</button><button className={kind === "buyer" ? "chosen" : ""} onClick={() => setKind("buyer")}>Buyers / Consignees ({buyers.length})</button></div><div className="manager-layout"><div className="profile-list">{profiles.map((p) => <div className={`profile-row ${p.id === selectedId ? "selected" : ""}`} key={p.id}><button className="profile-open" onClick={() => edit(p.id)}><b>{p.name}</b><small>{p.email || "No email saved"}</small></button><div className="profile-actions"><button title={`Edit ${p.name}`} aria-label={`Edit ${p.name}`} onClick={() => edit(p.id)}>✎</button><button title={`Delete ${p.name}`} aria-label={`Delete ${p.name}`} onClick={() => onDelete({ ...p, kind })}>⌫</button></div></div>)}</div><div className="profile-editor">{editing && selected ? <><div className="section-title"><div><small>EDIT {kind.toUpperCase()}</small><h2>{selected.name}</h2></div><button className="secondary" onClick={() => { setEditing(false); setSelectedId(""); }}>Close</button></div><div className="fields">{profileFields.map(([key, label]) => <Field key={key} field={[key, label, key === "address" ? "textarea" : "text"]} value={selected[key] || ""} onChange={(_, value) => update(key, value)} sellers={sellers} buyers={buyers} />)}</div></> : <div className="editor-empty"><h2>Select a {kind}</h2><p>Hover a row to use its Edit or Delete actions.</p></div>}</div></div><p className="message good">Profile updates save automatically. Selecting a profile in a form fills its latest saved details; old document values are not overwritten automatically.</p></section></div></main></div>;
}

function App() {
  const [files, setFiles] = useState(() => { try { return JSON.parse(localStorage.getItem("gurukrupan-export-files-v2")) || exportFiles; } catch { return exportFiles; } }); const [sellers, setSellers] = useState(() => { try { return JSON.parse(localStorage.getItem("gurukrupan-seller-profiles")) || defaultSellerProfiles; } catch { return defaultSellerProfiles; } }); const [buyers, setBuyers] = useState(() => { try { return JSON.parse(localStorage.getItem("gurukrupan-buyer-profiles")) || defaultBuyerProfiles; } catch { return defaultBuyerProfiles; } });
  const [fileId, setFileId] = useState(files[0]?.id || ""); const [active, setActive] = useState("purchaseOrder"); const [view, setView] = useState("dashboard"); const [notice, setNotice] = useState(""); const [confirm, setConfirm] = useState(null);
  const file = files.find((f) => f.id === fileId) || files[0]; const data = file?.data || clone(initialData); const step = documentSteps.find((s) => s.id === active); const schema = formSchemas[active]; const rows = data.documentItems?.[active] || []; const total = useMemo(() => rows.reduce((sum, r) => sum + (Number(r.amount) || 0), 0).toFixed(2), [rows]);
  useEffect(() => localStorage.setItem("gurukrupan-export-files-v2", JSON.stringify(files)), [files]); useEffect(() => localStorage.setItem("gurukrupan-seller-profiles", JSON.stringify(sellers)), [sellers]); useEffect(() => localStorage.setItem("gurukrupan-buyer-profiles", JSON.stringify(buyers)), [buyers]);
  const openFlow = (id) => { setFileId(id); setActive("purchaseOrder"); setView("form"); setNotice(""); };
  const newFlow = () => { const id = `new-${Date.now()}`; setFiles((all) => [...all, { id, label: `New export · DRAFT-${all.length + 1}`, customer: "", stage: "Draft", data: clone(initialData) }]); openFlow(id); };
  const removeConfirmed = () => { if (confirm.kind === "flow") { setFiles((all) => all.filter((f) => f.id !== confirm.id)); setFileId((current) => current === confirm.id ? "" : current); setView("dashboard"); } else if (confirm.kind === "seller") setSellers((all) => all.filter((p) => p.id !== confirm.id)); else setBuyers((all) => all.filter((p) => p.id !== confirm.id)); setConfirm(null); };
  const updateFile = (transform) => setFiles((all) => all.map((f) => f.id === file.id ? transform(f) : f));
  const startEditing = (fileData) => ({ ...fileData, completed: { ...fileData.completed, [active]: false } });
  const update = (key, value) => { if (profileKeys.includes(key)) { const profile = (key === "sellerProfileId" ? sellers : buyers).find((p) => p.id === value); if (!profile) return; const values = key === "sellerProfileId" ? { sellerProfileId: value, sellerName: profile.name, sellerAddress: profile.address } : { buyerProfileId: value, buyerName: profile.name, buyerAddress: profile.address, buyerContact: profile.contact, buyerEmail: profile.email }; updateFile((f) => ({ ...f, stage: "In progress", customer: key === "buyerProfileId" ? profile.name : f.customer, data: { ...f.data, ...startEditing(f.data), ...values } })); } else updateFile((f) => ({ ...f, stage: "In progress", data: { ...f.data, ...startEditing(f.data), [key]: value } })); };
  const updateRows = (nextRows) => updateFile((f) => ({ ...f, stage: "In progress", data: { ...f.data, ...startEditing(f.data), documentItems: { ...f.data.documentItems, [active]: nextRows } } }));
  const validate = () => { const missing = schema.filter(([key,,,required]) => required && !String(data[key] || "").trim()); if (missing.length) return setNotice(`Missing: ${missing.map(([, label]) => label).join(", ")}`); updateFile((f) => { const completed = { ...f.data.completed, [active]: true }; const allReady = documentSteps.every((item) => completed[item.id]); return { ...f, stage: allReady ? "Ready" : "In progress", data: { ...f.data, completed } }; }); setNotice(`${step.title} saved. ${documentSteps.every((item) => ({ ...data.completed, [active]: true })[item.id]) ? "All five forms are ready." : "The export flow remains in progress."}`); };
  if (view === "dashboard") return <><Dashboard files={files} onOpen={openFlow} onNew={newFlow} onDelete={(f) => setConfirm({ ...f, kind: "flow", name: f.label })} onProfiles={() => setView("profiles")} /><DeleteDialog item={confirm} onCancel={() => setConfirm(null)} onConfirm={removeConfirmed} /></>;
  if (view === "profiles") return <><Profiles sellers={sellers} buyers={buyers} setSellers={setSellers} setBuyers={setBuyers} onBack={() => setView("dashboard")} onDelete={(p) => setConfirm({ ...p, name: p.name })} /><DeleteDialog item={confirm} onCancel={() => setConfirm(null)} onConfirm={removeConfirmed} /></>;
  return <><div className="shell"><aside><div className="brand"><i>GA</i><div><b>Gurukrupan</b><small>Export documents</small></div></div><button className="new" onClick={() => setView("dashboard")}>← Dashboard</button><p className="nav-title">DOCUMENT SEQUENCE</p>{documentSteps.map((item, i) => <button key={item.id} className={`step ${active === item.id ? "active" : ""}`} onClick={() => { setActive(item.id); setNotice(""); }}><i>{data.completed?.[item.id] ? "✓" : i + 1}</i><span><b>{item.title}</b><small>{data.completed?.[item.id] ? "Validated - click to edit" : item.party}</small></span></button>)}</aside><main><header className="top"><div><p>{file.customer || "New export"} / {data.invoiceNo || "Draft"}</p><h1>{step.title}</h1></div><div className="tabs"><button className={view === "form" ? "chosen" : ""} onClick={() => setView("form")}>Edit form</button><button className={view === "preview" ? "chosen" : ""} onClick={() => setView("preview")}>A4 preview</button></div></header>{view === "form" ? <div className="content"><section className="summary"><div><small>SELLER</small><b>{data.sellerName}</b></div><div><small>CONSIGNEE</small><b>{data.buyerName}</b></div><div><small>DOCUMENT TOTAL</small><b>USD {total}</b></div><div><small>STATUS</small><b className={data.completed?.[active] ? "ready" : "draft"}>{data.completed?.[active] ? "Validated ✓" : "In progress"}</b></div></section><section className="card"><div className="section-title"><div><small>{step.party.toUpperCase()} · VARIABLE FIELDS</small><h2>Fields from this specific printed form</h2></div><button className="validate" onClick={validate}>Validate & save</button></div>{notice && <p className={`message ${notice.startsWith("Missing") ? "bad" : "good"}`}>{notice}</p>}<div className="fields">{schema.map((field) => <Field key={field[0]} field={field} value={data[field[0]]} onChange={update} sellers={sellers} buyers={buyers} />)}</div></section><GoodsTable active={active} rows={rows} onChange={updateRows} /><FixedText active={active} /></div> : <div className="preview-area"><div className="preview-bar"><span>Fixed text stays fixed. These values come from this document only.</span><div><button onClick={() => setView("form")}>Back to editing</button><button className="print" onClick={() => window.print()}>Print / save PDF</button></div></div><Preview active={active} data={data} /></div>}</main></div><DeleteDialog item={confirm} onCancel={() => setConfirm(null)} onConfirm={removeConfirmed} /></>;
}

export default App;
