export const company = { name: "GURUKRUPAN AGRO LIMITED", cin: "U01820GJ2020PLC118253", iec: "AAICG7050K", gstin: "24AAICG7050K1ZH", address: "OFFICE NO. 401, 4TH FLOOR, SHIVALIK-7, GONDAL ROAD, RAJKOT-360002, GUJARAT, INDIA.", phone: "+91 99048 16700", email: "ramguru.exports@gmail.com" };

export const documentSteps = [
  { id: "purchaseOrder", short: "PO", title: "PURCHASE ORDER", party: "Seller / supplier" },
  { id: "salesContract", short: "SC", title: "SALES CONTRACT", party: "Buyer / importer" },
  { id: "customsInvoice", short: "CI", title: "INVOICE / PACKING", party: "Customs / shipping" },
  { id: "commercialInvoice", short: "INV", title: "INVOICE", party: "Buyer / importer" },
  { id: "packingList", short: "PL", title: "PACKING LIST", party: "Buyer / importer" },
];

export const defaultSellerProfiles = [{ id: "seller-ramji", name: "RAMJI TRADING CO.", address: "1ST FLOOR, SHOP NO. A-179, SHREE SARDAR VALLABHBHAI PATEL MARKET YARD, MORBI ROAD, BEDI, RAJKOT, GUJARAT. PIN CODE: 360003", contact: "", email: "", gstin: "" }];
export const defaultBuyerProfiles = [{ id: "buyer-wgk", name: "WGK GENERAL TRADING L.L.C.", address: "DUBAI, UAE PO Box 10055", contact: "+971586872240", email: "operations.wgk@gmail.com", gstin: "" }];
export const profileFields = [["name", "NAME"], ["address", "ADDRESS"], ["contact", "CONTACT NO."], ["email", "E-MAIL ID"], ["gstin", "GSTIN / TAX ID"]];

export const fixedText = {
  purchaseOrder: ["For, Buyer                                      For, Seller", "TERMS & CONDITIONS:-", "1. Commodity must confirm to the Specific Quality & Weight.", "2. Shipping Marks printed on each bag well otherwise charges will be borne by seller AIC.", "3. All transport charges paid by the supplier prior to dispatch.", "4. PO must be provided with the documents, penalty for supplier failure.", "5. Subject to Rajkot Jurisdiction, Gujarat."],
  salesContract: ["We are ready and willing to supply the below mentioned Indian Commodities with full responsibility as per under stated Specifications and Terms & Conditions.", "DOCUMENTS REQUIRED: 1. INVOICE  2. PACKING LIST  3. CERTIFICATE OF ORIGIN  4. FUMIGATION CERTIFICATE  5. PHYTOSANITARY CERTIFICATE", "1. Delivery Terms: By sea, By Containers CNF Jebel Ali, UAE as per Incoterms 2020.", "2. This shipment is on a CNF basis, and no insurance has been arranged by us for the cargo. Therefore, all subsequent responsibility for the goods shall rest with the buyer.", "3. Packing: Export standard packing suitable for sea freight.", "4. Inspection: Pre-shipment inspection by Seller, third-party Inspection (SGS/BV) at buyer’s cost if buyer required.", "5. Quality Assurance: Goods shall conform to agreed specifications and Indian/international standards.", "6. Insurance: Arrange by Buyer, if they requires.", "7. Partial Shipment / Trans shipment: Not allowed.", "8. If there is any delay in shipment due to Shut Out of Containers, delay in normal schedule of Vessel, Buyer has to provide necessary extension of shipment, Seller shall not be responsible for any delay in transit over normal voyage time.", "9. Seller reserves the right to recall the documents if the same are not paid within 7 Calender days from the date of presentation.", "10. If Buyer fails to make payment of the documents as per Contract, the Seller reserves the right to protect his interest and accordingly this Contract acts as implied No Objection Certificate/Confirmation from Buyer to Seller to Transfer/Resell the Goods covered by this Contract to alternate Buyer. This clause therefore serve as valid No Objection Certificate to Customs or any statutory authorities to clear the Cargo. Under these circumstances, Seller can unconditionally choose to cancel the Contract and withdraw or re-route the documents and sell the Cargo as per the Seller's choice.", "11. This agreement is subject to Force Majeure if at any time during the continuation of this agreement either party is disabled to perform in whole or in part any obligation under this agreement because of Natural Disasters, Acts of God, War, Flood, Typhoon, Strike, Fire, Riots, Explosion, Government Regulation.", "12. No responsibility on the sellers for clearance of the goods at destination in any factor. Duties & Taxes in Country of destination to be for Buyer's account. All destuffing charges, THC/DDC at destination to be on Buyer's account.", "13. All disputes arising out of or in connection with the present contract shall be finally settled under the Rules of Arbitration of the FOSFA, London by one or more arbitrators appointed in accordance with the said Rules.", "14. The buyers agrees to pay the bills as per the terms above and if any overdue interests and cystalisations and other bank charges will be borne by the buyers."],
  customsInvoice: ["NOTE: GOODS CLEARED UNDER LETTER OF UNDERTAKING, Application submitted on GST portal ARN Num: AD2404260064296 UNDER RULE 96 IGST RULES, 2017.", "REMARKS: 1, SUPPLY MEANT FOR EXPORT WITHOUT PAYMENT OF IGST. 2) DUTY DRAWBACK IF APPLICABLE 3), WE INTEND TO CLAIM REWARDS UNDER REMISSION OF DUTIES & TAXES ON EXPORT PRODUCT (RoDTEP) IF APPLICABLE.", "DECLARATION: We declare that this INVOICE shows the actual price of the goods described and that all particulars are true and correct."],
  commercialInvoice: ["WE INTEND TO CLAIM REWARDS UNDER REMISSION OF DUTIES & TAXES ON EXPORT PRODUCT (RoDTEP) IF APPLICABLE.", "DECLARATION: We declare that this INVOICE shows the actual price of the goods described and that all particulars are True and Correct in all aspects."],
  packingList: ["DECLARATION: We declare that this INVOICE shows the actual price of the goods described and that all particulars are True and Correct in all aspects."],
};

export const formSchemas = {
  purchaseOrder: [["sellerProfileId", "SELLER", "sellerProfile", true], ["sellerName", "SELLER NAME", "text", true], ["sellerAddress", "SELLER ADDRESS", "textarea", true], ["poCommodity", "DESCRIPTION OF COMMODITY", "text", true], ["poQuantity", "QUANTITY"], ["poRate", "RATE"], ["poAmount", "AMOUNT"], ["poShippingMarks", "SHIPPING MARKS", "textarea"]],
  salesContract: [["buyerProfileId", "BUYER", "buyerProfile", true], ["buyerName", "BUYER NAME", "text", true], ["buyerAddress", "BUYER ADDRESS", "textarea", true], ["salesContainer", "FCL", "text", true], ["salesCommodity", "DESCRIPTION OF COMMODITIES", "text", true], ["salesQuantity", "QUANTITY"], ["salesPacking", "PACKING", "textarea"], ["salesRate", "RATE US$"], ["salesAmount", "TOTAL"], ["deliveryTerms", "DELIVERY TERMS", "text", true]],
  customsInvoice: [["invoiceNo", "INVOICE NO.", "text", true], ["invoiceDate", "INVOICE DT.", "date", true], ["buyerProfileId", "CONSIGNEE :-", "buyerProfile", true], ["buyerName", "CONSIGNEE NAME", "text", true], ["buyerAddress", "CONSIGNEE ADDRESS", "textarea", true], ["buyerContact", "CONTACT NO.:-"], ["buyerEmail", "E-MAIL ID:-"], ["notifyParty", "NOTIFY PARTY:-", "textarea"], ["paymentTerms", "PAYMENT TERMS", "text", true], ["container", "CONTAINER", "text", true], ["countryOrigin", "COUNTRY OF ORIGIN OF GOODS", "text", true], ["finalDestination", "COUNTRY OF FINAL DESTINATION", "text", true], ["portLoading", "PORT OF LOADING", "text", true], ["portDischarge", "PORT OF DISCHARGE", "text", true], ["commission", "COMMISSION"], ["totalPackages", "TOTAL PACKAGES"], ["totalNetWeight", "TOTAL WEIGHT / MT NET"], ["totalGrossWeight", "TOTAL WEIGHT / MT GROSS"], ["totalCnfValue", "TOTAL CNF VALUE IN US$"], ["amountWords", "AMOUNT IN WORDS", "textarea"]],
  commercialInvoice: [["billNo", "B/L NO."], ["billDate", "B/L DT.", "date"], ["shippingBillNo", "SB NO."], ["shippingBillDate", "SB DT.", "date"], ["invoiceNo", "INVOICE NO.", "text", true], ["invoiceDate", "INVOICE DT.", "date", true], ["buyerProfileId", "CONSIGNEE:", "buyerProfile", true], ["buyerName", "CONSIGNEE NAME", "text", true], ["buyerAddress", "CONSIGNEE ADDRESS", "textarea", true], ["buyerContact", "CONTACT NO.:-"], ["buyerEmail", "E-MAIL ID:-"], ["notifyParty", "NOTIFY PARTY:-", "textarea"], ["paymentTerms", "PAYMENT TERMS", "text", true], ["container", "CONTAINER", "text", true], ["countryOrigin", "COUNTRY OF ORIGIN", "text", true], ["finalDestination", "FINAL DESTINATION", "text", true], ["portLoading", "PORT OF LOADING", "text", true], ["placeDelivery", "PLACE OF DELIVERY", "text", true], ["portDischarge", "PORT OF DISCHARGE", "text", true], ["vesselVoyage", "VESSEL / VOYAGE"], ["marksAndNo", "MARKS & NO.", "textarea"], ["containerNo", "CONTAINER NO."], ["sealNo", "SEAL NO."], ["totalPackages", "PACKAGES"], ["totalNetWeight", "TOTAL NET WEIGHT"], ["totalGrossWeight", "TOTAL GROSS WEIGHT"], ["commission", "COMMISSION"], ["totalCnfValue", "TOTAL CNF VALUE IN USD:-"], ["amountWords", "AMOUNT IN WORDS", "textarea"]],
  packingList: [["billNo", "B/L NO."], ["billDate", "B/L DT.", "date"], ["shippingBillNo", "SB NO."], ["shippingBillDate", "SB DT.", "date"], ["invoiceNo", "INVOICE NO.", "text", true], ["invoiceDate", "INVOICE DT.", "date", true], ["buyerProfileId", "CONSIGNEE:-", "buyerProfile", true], ["buyerName", "CONSIGNEE NAME", "text", true], ["buyerAddress", "CONSIGNEE ADDRESS", "textarea", true], ["buyerContact", "CONTACT NO.:-"], ["buyerEmail", "E-MAIL ID:-"], ["notifyParty", "NOTIFY PARTY:-", "textarea"], ["paymentTerms", "PAYMENT TERMS", "text", true], ["container", "CONTAINER", "text", true], ["countryOrigin", "COUNTRY OF ORIGIN", "text", true], ["finalDestination", "FINAL DESTINATION", "text", true], ["portLoading", "PORT OF LOADING", "text", true], ["placeDelivery", "PLACE OF DELIVERY", "text", true], ["portDischarge", "PORT OF DISCHARGE", "text", true], ["vesselVoyage", "VESSEL / VOYAGE"], ["marksAndNo", "MARKS & NO.", "textarea"], ["containerNo", "CONTAINER NO."], ["sealNo", "SEAL"], ["totalPackages", "PACKAGES"], ["totalNetWeight", "TOTAL NET WEIGHT"], ["totalGrossWeight", "TOTAL GROSS WEIGHT"], ["commission", "COMMISSION"]],
};

export const tableHeaders = { customsInvoice: ["NO. & KIND OF PKGS", "DESCRIPTION OF COMMODITIES", "QUANTITY", "RATE US$", "AMOUNT"], commercialInvoice: ["KIND OF PKGS.", "DESCRIPTION OF COMMODITIES", "QUANTITY", "RATE USD", "AMOUNT"], packingList: ["KIND OF PKGS.", "DESCRIPTION OF COMMODITIES", "QUANTITY", "GROSS WT.", "REMARKS"] };
const goods = [{ id: "1", packages: "900 BAGS PACKED IN 10KGS PP BAGS EACH", description: "INDIAN BAY LEAF (TEJPATTA)\nHS CODE (09109990)", quantity: "9.000 MT NET", rate: "735.000", amount: "6615.00", gross: "9.900 MT GROSS", remarks: "N/A" }, { id: "2", packages: "50 BOXES. EACH 10 KG BOX CONTAINS 40 JARS OF 250 GRAMS EACH", description: "INDIAN BAY LEAF (TEJPATTA)\nHS CODE (09109990)", quantity: "0.500 MT NET", rate: "735.000", amount: "367.50", gross: "0.550 MT GROSS", remarks: "N/A" }];

export const initialData = { sellerProfileId: "seller-ramji", sellerName: "RAMJI TRADING CO.", sellerAddress: defaultSellerProfiles[0].address, buyerProfileId: "buyer-wgk", buyerName: "WGK GENERAL TRADING L.L.C.", buyerAddress: defaultBuyerProfiles[0].address, buyerContact: defaultBuyerProfiles[0].contact, buyerEmail: defaultBuyerProfiles[0].email, invoiceNo: "GAL/26-27/038", invoiceDate: "2026-07-25", billNo: "XXXXXXXXXXXX", billDate: "2026-07-30", shippingBillNo: "0", shippingBillDate: "2026-07-25", notifyParty: "XXXXXXXXXXXXXXXXXXXXX\nDUBAI, UAE.", paymentTerms: "AGAINST BL", container: "01X40' FCL", containerNo: "EITU1332739", sealNo: "000791", countryOrigin: "INDIA", finalDestination: "UAE", portLoading: "NHAVA SHEVA, INDIA", placeDelivery: "JEBEL ALI, UAE", portDischarge: "JEBEL ALI, UAE", vesselVoyage: "ESL WAFA / 026A9", commission: "01%", totalPackages: "950", totalNetWeight: "9.500 MT NET", totalGrossWeight: "10.450 MT GROSS", totalCnfValue: "6982.50", marksAndNo: "TEJ PATTA\nNET WT.: 10 KG\nPKG. DT: 02/2026\nEXP. DT: 02/2028\nORIGIN: INDIA", amountWords: "SIX THOUSAND, NINE HUNDRED EIGHTY TWO DOLLARS AND FIFTY CENTS ONLY", poCommodity: "FENNEL SEEDS", poQuantity: "", poRate: "", poAmount: "", poShippingMarks: "", salesContainer: '1X20 " FCL', salesCommodity: "INDIAN COFFEE BEANS ROBUSTA CHERRY-AA", salesQuantity: "19.200 MT", salesPacking: "640 BAGS PACKING IN 60 KG JUTE BAGS.", salesRate: "0.00", salesAmount: "0.00", deliveryTerms: "CNF JEBEL ALI, UAE", completed: {}, documentItems: { customsInvoice: goods, commercialInvoice: goods, packingList: goods } };
export const clone = (value) => JSON.parse(JSON.stringify(value));
export const exportFiles = [{ id: "gal-038", label: "WGK · GAL/26-27/038", customer: "WGK GENERAL TRADING L.L.C.", stage: "Invoices ready", data: clone(initialData) }];
